baseURL = "http://workout.mycontributes.online/"
languageCode = "en-us"
title = "Move, Exercise, Workout"
theme = "mainroad"
publishDir = "docs"
paginate= 100
googleAnalytics = "UA-170110346-1" # Enable Google Analytics by entering your tracking id


[Params]
  readmore = false # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  #toc = true # Enable Table of Contents
  pager = false # Show pager navigation (prev/next links) at the bottom of pages if true
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right" # "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "links", "categories", "collectionlist", "taglist", "musclelist", "progressionlist", "stretchlist", "equipmentlist", "flexibilitylist", "recent"]  #, "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[taxonomies]
  tag = "tags"
  category = "categories"
  collection = "collections"
  progression = "progressions"
  equipment = "equipment"
  muscle = "muscles"
  stretch = "stretches"
  flexibility = "flexibilities"
